import './global.css';

export const metadata = {
  title: 'Projects',
  description: 'Generated by create-nx-workspace',
  icons: { icon: '/joe-head.png' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
